name: Create Server Notebook

on:
  workflow_dispatch:
    inputs:
      server_name:
        description: "Server name"
        required: true
      server_version:
        description: "Minecraft version"
        required: true
      server_software:
        description: "Server software"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create servers folder
        run: mkdir -p servers/${{ github.event.inputs.server_name }}

      - name: Generate Colab Notebook
        run: |
          cat > servers/${{ github.event.inputs.server_name }}/start_server.ipynb <<'EOF'
          {
            "cells": [
              {
                "cell_type": "markdown",
                "metadata": {},
                "source": ["# Start Minecraft Server"]
              },
              {
                "cell_type": "code",
                "metadata": {},
                "source": [
                  "!wget https://papermc.io/api/v2/projects/${{ github.event.inputs.server_software }}/versions/${{ github.event.inputs.server_version }}/builds/latest/download -O server.jar\n",
                  "!java -Xmx2G -Xms1G -jar server.jar nogui"
                ]
              }
            ],
            "metadata": {
              "colab": {
                "name": "Start Server"
              },
              "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
              }
            },
            "nbformat": 4,
            "nbformat_minor": 0
          }
          EOF

      - name: Commit notebook
        run: |
          git config user.name "LunarHost Bot"
          git config user.email "bot@lunarhost520.github.io"
          git add servers/${{ github.event.inputs.server_name }}/start_server.ipynb
          git commit -m "Add notebook for ${{ github.event.inputs.server_name }}"
          git push
