name: Create Server Notebook

on:
  workflow_dispatch:
    inputs:
      server_name:
        description: "Server name"
        required: true
        type: string
      server_version:
        description: "Minecraft version"
        required: true
        type: string
      server_software:
        description: "Server software (paper/purpur/fabric/forge)"
        required: true
        type: string

jobs:
  create-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create server folder
        run: mkdir -p servers/${{ github.event.inputs.server_name }}

      - name: Generate Colab Notebook
        run: |
          cat > servers/${{ github.event.inputs.server_name }}/start_server.ipynb <<'EOF'
          {
            "cells": [
              {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                  "# Minecraft Server - ${{ github.event.inputs.server_name }}",
                  "",
                  "Version: ${{ github.event.inputs.server_version }}",
                  "",
                  "Software: ${{ github.event.inputs.server_software }}"
                ]
              },
              {
                "cell_type": "code",
                "metadata": {},
                "source": [
                  "!wget https://api.papermc.io/v2/projects/${{ github.event.inputs.server_software }}/versions/${{ github.event.inputs.server_version }}/builds/latest/download -O server.jar\n",
                  "!java -Xmx2G -Xms1G -jar server.jar nogui"
                ]
              }
            ],
            "metadata": {
              "colab": {
                "name": "Start Minecraft Server"
              },
              "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
              }
            },
            "nbformat": 4,
            "nbformat_minor": 0
          }
          EOF

      - name: Commit and Push
        run: |
          git config user.name "LunarHost Bot"
          git config user.email "bot@lunarhost520.github.io"
          git add servers/${{ github.event.inputs.server_name }}/start_server.ipynb
          git commit -m "
